### ISSUE TITLE
VAP in disag_pa_2020.ipynb

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/election-disag#3]
@rdhlily  I want to compare election results in different years at block-level, but one of the difficulties is that many population data aren't available when a year doesn't coincide with the decennial Census.  Many population data are also unavailable to derive CVAP from VAP, in any year when the Census Bureau didn't estimate CVAP.

For blocks within where correctional facilities are located, some blocks have population that are predominately or entirely disenfranchised.  In such disenfranchised blocks, should VAP subtract (not reallocate) the prisoner population?  If yes, then would it cause a problem when comparing with the election results of other years?  Thanks.

**Comment by rdhlily** [comment]
Hi @rootsmusic, Thanks for the question!

In other states our disaggregation method calculates the voting population by subtracting the Census "P0050003" (total incarcerated pop) variable from the "P0040001" (VAP TOT) variable, as I believe you described. In the case of Pennsylvania, because the state did release a state adjusted file, the RDH used the updated geospatial data from the state where some Census blocks were split, but where the incarcerated population was not reallocated.  Our modified VAP variable ("VAP_MOD" from our file) was then calculated using the ratio of the total population in the split blocks from the original Census file and the updated split file, and that ratio was applied to P0040001.

As for your question about comparison with other years, the base year for the block file is a consideration, but we plan to use the 2020 Census PL data for election results after 2015, and 2010 Census PL data for prior. In either case we do not anticipate using reallocated data.

**Comment by rootsmusic** [comment]
Yes @rdhlily, I agree with this notebook's shapefile not reallocating prisoners.  If you disaggregate 2022 election results, I'll suggest using L2's block-level total_reg instead of VAP because VAP includes several populations that aren't eligible to vote.  Regarding one such ineligible population, the registration status of those who were disenfranchised would have been "cancelled" in the voter roll and hence excluded by L2's total_reg.

**Comment by rdhlily** [comment]
This is a good point! There were a few reasons we chose to use the PL data from the start, but we will revisit those reasons and continue to evaluate moving forward. Thanks for raising this concern!

**Comment by rootsmusic** [comment]
You're welcome!  If RDH revisits my suggestion, I'd recommend first assessing the quality of L2's geocoding because my suggestion assumes L2's data processing is dependable.

P.S. PA's official district assignments for 2018 GE is at https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_2018_G(114234)_20190726.txt

**Comment by rootsmusic** [comment]
rdhlily wrote:
> we plan to use the 2020 Census PL data for election results after 2015, and 2010 Census PL data for prior.

@rdhlily  Substituting the decennial VAP (itself already an imperfect substitute for the voter registration) for intercensal years, especially further years.  Are VAP estimates for intercensal years not available from HaystaqDNA?

P.S. PA's official district assignments for 2018 GE is at https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_2018_G(114234)_20190726.txt

**Comment by rootsmusic** [comment]
rdhlily wrote:
> we plan to use the 2020 Census PL data for election results after 2015, and 2010 Census PL data for prior.

I compared the Census Bureau's 2020 VAP (in PL 94-171) against 2018 VAP (in [Evaluation Estimates](https://www.census.gov/programs-surveys/popest/technical-documentation/research/evaluation-estimates/2020-evaluation-estimates/2010s-county-detail.html)) to calculate your assumption's error rate.  At county-level, the error rate from this single assumption (not accounting for the assumption that VAP, itself, would be a faithful proxy for the number of registered voters who voted) could be as high as 9.8%.  Since you've already disaggregated [2018 CVAP estimates to 2020 blocks](https://redistrictingdatahub.org/dataset/pennsylvania-cvap-data-disaggregated-to-the-2020-block-level-2018/), would 2018 CVAP be more accurate than your assumption?


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



COUNTY | VAP   % change
-- | --
113 | -9.8%
053 | -8.6%
119 | -6.3%
115 | -6.3%
031 | -4.7%
043 | 4.7%
067 | -4.2%
047 | 4.1%
035 | -4.0%
091 | 3.9%
069 | 3.8%
103 | 3.4%
131 | -3.3%
019 | 3.2%
095 | 3.2%
061 | -3.1%
003 | 3.1%
017 | 3.0%
041 | 3.0%
101 | 3.0%
027 | -3.0%
079 | 2.9%
065 | 2.8%
109 | -2.7%
121 | -2.6%
077 | 2.5%
007 | 2.5%
123 | -2.3%
071 | 2.3%
063 | -2.3%
029 | 2.3%
011 | 2.2%
075 | 2.1%
021 | 2.1%
133 | 2.0%
045 | 2.0%
107 | 2.0%
083 | -1.6%
125 | 1.4%
089 | -1.4%
033 | 1.3%
039 | -1.2%
009 | -1.2%
037 | -1.2%
129 | 1.2%
015 | -1.1%
023 | 1.1%
001 | 1.0%
099 | -0.9%
025 | 0.9%
013 | 0.9%
059 | -0.9%
057 | -0.7%
051 | -0.7%
127 | -0.6%
087 | 0.6%
105 | -0.6%
055 | 0.5%
005 | 0.5%
117 | 0.4%
093 | -0.4%
049 | 0.2%
085 | -0.2%
073 | 0.1%
111 | 0.1%
097 | 0.0%
081 | 0.0%
Grand   Total | 1.9%



</body>

</html>

**Comment by rdhlily** [comment]
@rootsmusic , We chose to stick with non-modeled data to avoid any error incurred in nested methods. In addition, we do not have modeled data prior to 2019 at the block level, and also will note a likely large difference at the block level compared with county level data.

**Comment by rootsmusic** [comment]
@rdhlily wrote:
>  we do not have modeled data prior to 2019 at the block level, and also will note a likely large difference at the block level compared with county level data.

Which "county level data" are you referring to?  You have already disaggregated [2018 CVAP to 2020 blocks](https://redistrictingdatahub.org/dataset/pennsylvania-cvap-data-disaggregated-to-the-2020-block-level-2018/).  When disaggregating election results for 2018, that year's CVAP would be a more accurate substitute of the same year's voter registration than a different year's VAP would be.

**Comment by rdhlily** [comment]
@rootsmusic , county referring to the example you provided above. While we did consider using the CVAP data, 2018 CVAP to 2020 Blocks dataset is disaggregated based on the blocks 2010 VAP to 2010 block group VAP ratio, then crosswalked from 2010 blocks to 2020 blocks. We are not convinced that using data that is 1) using a 5-Year estimate, 2) disaggregated to the block level using a 2010 ratio, 3) crosswalked to current blocks, provides less error than using VAP from 2020. This would be a very interesting case to test, but unfortunately we do not have the time.

In addition, 2018 CVAP data really is actually best representative of the year 2016, since that would be the mid-point of the five years. so in reality, if we were to do this method, we *should* actually use 2020 CVAP for 2018, it would be more accurate.
