### ISSUE TITLE
district_mismatch_report

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/election-disag#4]
I'm trying to interpret this function's output.  [Your metadata](https://redistrictingdatahub.org/wp-content/uploads/2022/03/readme_az_20_block.txt) explains, "This file contains two separate district assignments for each census block: the Census district assignment and an RDH-calculated 'precinct-based' district assignment."  But it didn't define how you calculated the precinct-based district assignment.

Your metadata offers a couple explanations for mismatched districts, where actual votes in mismatched blocks were impacted.  Could an explanation be that the shapefile's precinct boundaries aren't accurate, in terms of whether they geometrically match the election's finalized boundaries?

**Comment by rootsmusic** [comment]
After thinking more, I think that the mismatch doesn't indicate the Census' boundaries are accurate either.

**Comment by rdhlily** [comment]
Apologies for the confusion - the 'precinct-based' district assignment uses maup assign to assign the district boundaries from the precinct file to the block file employing the same method as assigning the precinct boundaries to the block file. The Census district boundaries are not necessarily correct which is why we drew this distinction. Ultimately, if a user wants to know about precise district boundaries they should load in a district file separately to their mapping software and overlay the block file with the district file.

**Comment by rootsmusic** [comment]
(@rdhlily Just a note, in case you're unaware.)  For PA's 2020 GE, the Department of State includes district assignments in `./raw-from-source/ERStat_2020_G(179507)_20210505.txt` (with a [field layout](https://github.com/openelections/openelections-sources-pa/blob/master/2020/general/ERStat_readme.txt) archived by OpenElections, along with similar files for other elections) for vest_pa_20_replication_state_file.ipynb.  Those district assignments have changes made after the state proposed VTDs to the Census Bureau.

**Comment by rdhlily** [comment]
Thanks for linking!
